function 初始主要属性(){
	var _loc4_ = new Object();
	故事 = _loc4_;
	var _loc3_ = new Object();
	_loc3_.年龄 = 18;
	_loc3_.健康 = 80 + Math.round(Math.random()*20);
	_loc3_.状态 = "健康";
	_loc3_.体力 = 160 + Math.round(Math.random()*30);
	_loc3_.体力上限 = _loc3_.体力;
	_loc3_.快乐 = 100;
	_loc3_.威望 = 100 + Math.round(Math.random()*50);
	_loc3_.统帅 = 90 + Math.round(Math.random()*10);
	_loc3_.武力 = 90 + Math.round(Math.random()*10);
	_loc3_.智力 = 90 + Math.round(Math.random()*10);
	_loc3_.政治 = 90 + Math.round(Math.random()*10);
	_loc3_.魅力 = 20 + Math.round(Math.random()*10);
	_loc3_.暴戾 = 20 + Math.round(Math.random()*10);
	_loc3_.道德 = 20 + Math.round(Math.random()*10);
	_loc3_.才艺 = 90 + Math.round(Math.random()*10);
	_loc3_.寿命 = 600 + Math.round(Math.random()*90);
	属性 = _loc3_;
	季 = 1;
	年 = 1;
	月 = 1;
	旬 = "上旬";
	var _loc2_ = new Object();
	_loc2_.大殿 = 1;
	_loc2_.丹药 = [];
	_loc2_.负数时间 = 0;
	_loc2_.丹药列表 = undefined;
	_loc2_.炼制 = [0,0,0,0,0,0,0,0];
	_loc2_.有客人 = [0,undefined];
	_loc2_.研发技术 = 0;
	_loc2_.解语花 = 0;
	_loc2_.黑瞎子 = 0;
	_loc2_.吴邪 = 0;
	_loc2_.张起灵 = 0;
	_loc2_.小王爷 = 0;
	_loc2_.一枝梅 = 0;
	_loc2_.摩葛可汗 = 0;
	_loc2_.倚梅园 = 0;
	_loc2_.小燕子 = 0;
	_loc2_.吕四娘 = 0;
	_loc2_.嘉宁 = 0;
	_loc2_.曹夙峰 = 0;
	_loc2_.红星寿 = 0;
	_loc2_.谢衣 = 0;
	_loc2_.鱼美人 = 0;
	_loc2_.武媚娘 = 0;
	_loc2_.武如意 = 0;
	_loc2_.苏茉尔 = 0;
	_loc2_.亚瑟 = 0;
	_loc2_.泉灵 = 0;
	_loc2_.展昭 = 0;
	_loc2_.朝旭 = 0;
	_loc2_.李枫 = 0;
	_loc2_.梅长苏 = 0;
	_loc2_.顾惜朝 = 0;
	_loc2_._relation_chenwangyan = 5;
	_loc2_._relation_caosufeng = 5;
	_loc2_._relation_hongxingshou = 5;
	_loc2_._relation_xieyi = 5;
	_loc2_._relation_sumoer = 5;
	_loc2_._con_tianjiang = 0;
	_loc2_._con_tjshangxian = 4;
	_loc2_.冷宫 = [];
	_loc2_.追封 = [];
	_loc2_.掖庭 = [];
	_loc2_.后宫 = [];
	_loc2_.当前时辰 = 0;
	_loc2_._anquan = 0;
	_loc2_._huangyin = 0;
	_loc2_._yinntiki = 0;
	_loc2_.战报 = "";
	_loc2_.战斗队伍 = new Object();
	_loc2_.生病次数 = 0;
	_loc2_.祭祀 = 0;
	_loc2_.出战 = 0;
	远嫁公主 = [];
	_all_feizi = [];
	_all_rencai = [];
	_all_child = [];
	_all_grandchild = [];
	_all_family = [];
	血滴子 = [];
	_all_taijian = [];
	_all_gongnv = [];
	_all_army = [];
	_all_party = [];
	 _loc2_.事件库 = {};
	主角 = _loc2_;
	var _loc2_ = new Object();
	_loc2_.金钱 = 800000000;
	_loc2_.粮食 = 1000000000;
	_loc2_.朴刀 = 13000;
	_loc2_.皮甲 = 5000;
	_loc2_.战马 = 3000;
	_loc2_.铁炮 = 3000;
	_loc2_.弓弩 = 1000;
	_loc2_.长枪 = 3000;
	_loc2_.民夫 = 100000;
	_loc2_.特殊建筑民夫 = 0;
	_loc2_.可用民夫 = _loc2_.民夫 - _loc2_.特殊建筑民夫;
	_loc2_.士兵 = 30000 + random(500);
	_loc2_.训练 = 50;
	_loc2_.朴刀操作 = 0;
	_loc2_.皮甲操作 = 0;
	_loc2_.战马操作 = 0;
	_loc2_.铁炮操作 = 0;
	_loc2_.训练周期 = 0;
	_loc2_.安全检视 = 0;
	_loc2_.选秀 = 0;
	_loc2_.目前出征的皇子 = undefined;
	_loc2_.钦差 = undefined;
	_loc2_.青樱的姐姐 = undefined;
	_loc2_.接受挑战的人 = undefined;
	_loc2_.皇储id = undefined;
	_loc2_.嘉宁出征 = 0;
	_loc2_.遇到山贼 = 0;
	_loc2_.协理六宫 = ["无",50];
	_loc2_.供药局 = 0;
	_loc2_.皇子顺序 = 1;
	_loc2_.公主顺序 = 1;
	_loc2_.子女顺序 = 2;
	_loc2_.妃子顺序 = 4;
	_loc2_.臣子顺序 = 0;
	_loc2_.汤泉宫 = 0;
	_loc2_.铜雀台 = 0;
	_loc2_.事件一 = 0;
	_loc2_.事件二 = 0;
	_loc2_.事件三 = 0;
	_loc2_.事件四 = 0;
	_loc2_.事件五 = 0;
	_loc2_.事件六 = 0;
	_loc2_.事件七 = 0;
	_loc2_.事件八 = 0;
	_loc2_.事件九 = 0;
	_loc2_.事件10 = 0;
	国家 = _loc2_;
	战争结局 = {};
	城市升级喜报 = undefined;
	修养 = ["优+","优","优-","良+","良","良-","中+","中","中-","差+","差","差-"];
	后宫位分备份 = [[0,"皇后",1,0],[1,"皇贵妃",1,0],[2,"贵妃",2,0],[3,"妃",4,0],[4,"九嫔",9,0],[5,"嫔",9,0],[6,"贵人",9999,0],[7,"美人",9999,0],[8,"才人",9999,0],[9,"御女",9999,0],[10,"采女",9999,0],[11,"官女",9999,0]];
	后宫位分 = [[0,"皇后",1,0],[1,"皇贵妃",1,0],[2,"贵妃",2,0],[3,"妃",4,0],[4,"九嫔",6,0],[5,"嫔",6,0],[6,"贵人",9999,0],[7,"美人",9999,0],[8,"才人",9999,0],[9,"御女",9999,0],[10,"采女",9999,0],[11,"官女",9999,0]];
}
初始主要属性();
ID=[];
九嫔位分 = [[0.1,"昭仪",0,0],[0.2,"昭容",1,0],[0.3,"昭媛",2,0],[0.4,"淑仪",3,0],[0.5,"淑媛",4,0],[0.6,"淑容",5,0],[0.7,"修仪",6,0],[0.8,"修媛",7,0],[0.9,"修容",8,0]];
var i = 0;
while(i < 18){
   var 放入谁 = undefined;
   var 生成年龄 = random(6) + 14;
   if(i == 0){  
      放入谁 = {id:0,_code:7009,地位:后宫位分[i][0],位分:后宫位分[i][1],封号:"宜德",宫殿:0,寝殿:0,家族:"朱",党:0,名字:"朱宜修",文化:8,介绍:"原配皇后。是原太子妃朱柔则去世之后被立为皇后的，原太子妃的一双儿女过继给了她。",性别:1,统帅:random(99),武力:random(99),智力:random(99),政治:random(99),魅力:95,清廉:random(99),野心:random(99),经验:210,年龄:18,喜好:0,状态:0,性格:剧情人物[9].性格,出身:出身计算(2),头像:39,爱:300,孕:0,病:0,仙:0,生育:2,任性:random(50),后宫相性:"",后宫势力:0,朝廷相性:"",朝廷势力:0,皇嗣相性:"",护:0};
      _all_feizi.push(放入谁);
   }
   else if(i == 3){
      放入谁 = {id:1,_code:7012,地位:后宫位分[i][0],位分:后宫位分[i][1],封号:"如",宫殿:3,寝殿:0,家族:"萧",党:0,名字:"萧忆茹",文化:8,介绍:剧情人物[12].介绍,性别:1,统帅:剧情人物[12].统帅,武力:剧情人物[12].武力,智力:剧情人物[12].智力,政治:剧情人物[12].政治,魅力:剧情人物[12].魅力,清廉:剧情人物[12].清廉,野心:剧情人物[12].野心,经验:60,年龄:17,喜好:0,状态:0,性格:剧情人物[12].性格,出身:出身计算(2),头像:剧情人物[12].跳,爱:220,孕:0,病:4,仙:0,生育:0,任性:random(50),后宫相性:"",后宫势力:0,朝廷相性:"",朝廷势力:0,皇嗣相性:"",护:0};
	  _all_feizi.push(放入谁);
   }
   else if(i == 5){
      放入谁 = {id:2,_code:7013,地位:后宫位分[i][0],位分:后宫位分[i][1],封号:"莺",宫殿:2,寝殿:2,家族:"寒",党:0,名字:"寒梦莺",文化:8,介绍:剧情人物[13].介绍,性别:1,统帅:剧情人物[13].统帅,武力:剧情人物[13].武力,智力:剧情人物[13].智力,政治:剧情人物[13].政治,魅力:剧情人物[13].魅力,清廉:剧情人物[13].清廉,野心:剧情人物[13].野心,经验:20,年龄:16,喜好:0,状态:0,性格:剧情人物[13].性格,出身:"平民孤女",头像:剧情人物[13].跳,爱:160,孕:9,病:0,仙:2,生育:0,任性:random(50),后宫相性:"",后宫势力:0,朝廷相性:"",朝廷势力:0,皇嗣相性:"",护:0};
	  _all_feizi.push(放入谁);
   }
   else if(i == 7){
      放入谁 = {id:3,_code:7014,地位:后宫位分[i][0],位分:后宫位分[i][1],封号:"萱",宫殿:1,寝殿:2,家族:"陈",党:0,名字:"陈小萱",文化:8,介绍:剧情人物[14].介绍,性别:1,统帅:剧情人物[14].统帅,武力:剧情人物[14].武力,智力:剧情人物[14].智力,政治:剧情人物[14].政治,魅力:剧情人物[14].魅力,清廉:剧情人物[14].清廉,野心:剧情人物[14].野心,经验:10,年龄:14,喜好:0,状态:0,性格:剧情人物[14].性格,出身:出身计算(1),头像:剧情人物[14].跳,爱:92,孕:0,病:0,仙:0,生育:0,任性:random(50),后宫相性:"",后宫势力:0,朝廷相性:"",朝廷势力:0,皇嗣相性:"",护:0};
	  _all_feizi.push(放入谁);
   }
   i++;
}
_all_palace = [];
_all_palace.push({id:0,名称:"椒房殿",内殿:[''],殿:[undefined,undefined,undefined,undefined,undefined],等级:3,跳:1});
_all_palace.push({id:1,名称:"昭阳宫",内殿:["鸣鸾殿",殿[random(殿.length)],殿1[random(殿1.length)],殿[random(殿.length)],殿[random(殿.length)]],殿:[undefined,undefined,undefined,undefined,undefined],等级:3,跳:2});
_all_palace.push({id:2,名称:"关雎宫",内殿:["丽正殿",殿[random(殿.length)],殿1[random(殿1.length)],殿[random(殿.length)],殿[random(殿.length)]],殿:[undefined,undefined,undefined,undefined,undefined],等级:3,跳:3});
_all_palace.push({id:3,名称:"未央宫",内殿:["柔仪殿",殿[random(殿.length)],殿1[random(殿1.length)],殿[random(殿.length)],殿[random(殿.length)]],殿:[undefined,undefined,undefined,undefined,undefined],等级:3,跳:4});
_all_palace.push({id:4,名称:"翊坤宫",内殿:["惊鸿殿",殿[random(殿.length)],殿1[random(殿1.length)],殿[random(殿.length)],殿[random(殿.length)]],殿:[undefined,undefined,undefined,undefined,undefined],等级:3,跳:5});
_all_palace.push({id:5,名称:"蓬莱宫",内殿:["漪兰殿",殿[random(殿.length)],殿1[random(殿1.length)],殿[random(殿.length)],殿[random(殿.length)]],殿:[undefined,undefined,undefined,undefined,undefined],等级:3,跳:6});
_all_palace.push({id:6,名称:"甘泉宫",内殿:["含德殿",殿[random(殿.length)],殿1[random(殿1.length)],殿[random(殿.length)],殿[random(殿.length)]],殿:[undefined,undefined,undefined,undefined,undefined],等级:2,跳:7});
_all_palace.push({id:7,名称:"步寿宫",内殿:["雍和殿",殿[random(殿.length)],殿1[random(殿1.length)],殿[random(殿.length)],殿[random(殿.length)]],殿:[undefined,undefined,undefined,undefined,undefined],等级:2,跳:8});
_all_palace.push({id:8,名称:"长乐宫",内殿:["栖鸾殿",殿[random(殿.length)],殿1[random(殿1.length)],殿[random(殿.length)],殿[random(殿.length)]],殿:[undefined,undefined,undefined,undefined,undefined],等级:2,跳:9});
_all_palace.push({id:9,名称:"瑶华宫",内殿:["承欢殿",殿[random(殿.length)],殿1[random(殿1.length)],殿[random(殿.length)],殿[random(殿.length)]],殿:[undefined,undefined,undefined,undefined,undefined],等级:2,跳:10});
_all_palace.push({id:10,名称:"玉芙宫",内殿:["披香殿",殿[random(殿.length)],殿1[random(殿1.length)],殿[random(殿.length)],殿[random(殿.length)]],殿:[undefined,undefined,undefined,undefined,undefined],等级:2,跳:11});
_all_palace.push({id:11,名称:"碧霄宫",内殿:["锦瑟殿",殿[random(殿.length)],殿1[random(殿1.length)],殿[random(殿.length)],殿[random(殿.length)]],殿:[undefined,undefined,undefined,undefined,undefined],等级:1,跳:12});
_all_palace.push({id:12,名称:"缀霞宫",内殿:["千秋殿",殿[random(殿.length)],殿1[random(殿1.length)],殿[random(殿.length)],殿[random(殿.length)]],殿:[undefined,undefined,undefined,undefined,undefined],等级:1,跳:13});
_all_palace.push({id:13,名称:"太平宫",内殿:["霁月殿",殿[random(殿.length)],殿1[random(殿1.length)],殿[random(殿.length)],殿[random(殿.length)]],殿:[undefined,undefined,undefined,undefined,undefined],等级:1,跳:14});
_all_palace.push({id:14,名称:"仙都宫",内殿:["仙游殿",殿[random(殿.length)],殿1[random(殿1.length)],殿[random(殿.length)],殿[random(殿.length)]],殿:[undefined,undefined,undefined,undefined,undefined],等级:1,跳:15});
_all_palace.push({id:15,名称:"翠微宫",内殿:["晏昵殿",殿[random(殿.length)],殿1[random(殿1.length)],殿[random(殿.length)],殿[random(殿.length)]],殿:[undefined,undefined,undefined,undefined,undefined],等级:1,跳:16});
_all_palace.push({id:16,名称:"",殿:[undefined,undefined,undefined,undefined,undefined],等级:0,跳:17});
_all_palace.push({id:17,名称:"",殿:[undefined,undefined,undefined,undefined,undefined],等级:0,跳:18});
_all_palace.push({id:18,名称:"",殿:[undefined,undefined,undefined,undefined,undefined],等级:0,跳:19});
_all_palace.push({id:19,名称:"",殿:[undefined,undefined,undefined,undefined,undefined],等级:0,跳:20});
_all_palace.push({id:20,名称:"",殿:[undefined,undefined,undefined,undefined,undefined],等级:0,跳:21});
_all_palace.push({id:21,名称:"",殿:[undefined,undefined,undefined,undefined,undefined],等级:0,跳:22});
_all_palace.push({id:22,名称:"",殿:[undefined,undefined,undefined,undefined,undefined],等级:0,跳:23});
_all_palace.push({id:23,名称:"",殿:[undefined,undefined,undefined,undefined,undefined],等级:0,跳:24});
_all_palace.push({id:24,名称:"",殿:[undefined,undefined,undefined,undefined,undefined],等级:0,跳:25});
_all_palace.push({id:25,名称:"",殿:[undefined,undefined,undefined,undefined,undefined],等级:0,跳:26});
_all_palace.push({id:26,名称:"",殿:[undefined,undefined,undefined,undefined,undefined],等级:0,跳:27});
_all_palace.push({id:27,名称:"",殿:[undefined,undefined,undefined,undefined,undefined],等级:0,跳:28});
_all_palace.push({id:28,名称:"",殿:[undefined,undefined,undefined,undefined,undefined],等级:0,跳:29});
_all_palace.push({id:29,名称:"",殿:[undefined,undefined,undefined,undefined,undefined],等级:0,跳:30});
_all_palace.push({id:30,名称:"",殿:[undefined,undefined,undefined,undefined,undefined],等级:0,跳:31});
_all_palace.push({id:31,名称:"",殿:[undefined,undefined,undefined,undefined,undefined],等级:0,跳:32});
_all_palace.push({id:32,名称:"",殿:[undefined,undefined,undefined,undefined,undefined],等级:0,跳:33});
var i = 0;
while(i < _all_palace.length){
  var linshicanshu = _all_palace[i].id;
 _all_palace[i].次数 = 0;
 i++;
}
function random(m){r = Math.round(Math.random()*(m-1));return r;}
更新时辰的执行程序();
更新季节的程序呢();